### ISSUE TITLE
Erro no select de idioma

### ISSUE THREAD

**Issue by brunosk** [santospatrick/santospatrick.github.io#1]
Linux Mint 18 
Chrome Versão 68.0.3440.75

![image](https://user-images.githubusercontent.com/31865593/47297168-bb863b00-d5ea-11e8-95e1-24dd44272ebe.png)

**Comment by santospatrick** [comment]
![image](https://user-images.githubusercontent.com/13510169/47428114-acc59280-d768-11e8-9e16-97678d5f649b.png)
